language: python

python:
    - "3.4"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install flask
    - pip install angel
    - pip install sqlalchemy

before_script:
    - uname -a
    - printenv
    - pip list

script:
    - date
    - ls -al
    - make check
