
app:
  restart: always
  build: ./app
  container_name: series-z-flask
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/static
  env_file: postgres-config.env
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

nginx:
  restart: always
  build: ./nginx/
  container_name: series-z-nginx
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - app
  links:
    - app:app

data:
  image: postgres:latest
  container_name: series-z-data
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  container_name: series-z-postgres
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"
